# maincode.yaml
# Basic configuration file

# Event triggers
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Manual trigger

# Application settings
application:
  name: MainCode
  version: 1.0.0
  environment: development
  debug: true

# Server configuration
server:
  host: localhost
  port: 8080
  timeout: 30
  max_connections: 100

# Database configuration
database:
  driver: postgres
  host: db.example.com
  port: 5432
  name: maincode_db
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool:
    max_size: 20
    idle_timeout: 300

# Logging configuration
logging:
  level: info
  file: /var/log/maincode.log
  rotate:
    max_size: 100MB
    max_files: 10
    max_age: 30

# Feature flags
features:
  enable_new_ui: true
  enable_analytics: false
  enable_notifications: true

# API endpoints
endpoints:
  - name: users
    path: /api/v1/users
    methods: [GET, POST, PUT, DELETE]
    rate_limit: 100
  - name: products
    path: /api/v1/products
    methods: [GET, POST]
    rate_limit: 200

# Cache settings
cache:
  type: redis
  host: cache.example.com
  port: 6379
  ttl: 3600

# Actions to run when triggers fire
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: |
          npm install
          npm run setup
      - name: Run tests
        run: npm test
      - name: Build application
        run: npm run build
